-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "billDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "billNo" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "partyName" TEXT,
ADD COLUMN     "paymentMethod" TEXT NOT NULL DEFAULT 'Cash',
ADD COLUMN     "phoneNo" TEXT;
